mesage = "!Hello Python Crash Course reader!"

print(mesage) # Quando houver um erro em seu programa, o interpretador Python faz o melhor que puder para ajudar a vocÊ descobrir onde está o problema. O interpretador oferece um trackback quando um programa não é capaz de executar com sucesso. Um trackback é um registro do ponto em que o interpretador se deparou com o problemas quando tentou executar seu código. Eis um exemplo do trackback fornecido por Python após o nome da variável ter sido digitado incorretamente por engano: Traceback ( most recent call last): File "hello_world.py", line 2, in <module> / print (mesage) / NameError: Name 'mesage'is not defined A saida em informar que um erro ocorreu na linha 2 do arquivo hello_world.py. o interpretador mostra essa linha para nos ajudar a identificar o erro rapidamente / e informar o tipo de erro encontrado /. Nesse caso, ele encontrou um erro de nome e informa que a variável exibida, mesage, não foi definida. Python não é capaz de identificar o nome da variável especificada. Um erro de nome geralmente quer dizer que esquecemos de definir o valor de uma variável antes de usá-lá ou que cometemos um erro de ortografia quando fornecemos o nome da variável.
# A melhor maneira de entender novos conceitos de programação é tentar usá-los em seus programas. Se não souber o que fazer quando estiver trabalhando em seus exercicios desse matérial, procure dedicar-se a outra tarefa por um tempo. Se continuar sem conseguir avançar, analise a parte relevante do capitulo. Se ainda precisar de ajuda, Veja sugestões no Apêndice C.